package com.powilliam.mypackages.ui.theming

import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.ui.graphics.Color

val LightColorScheme = lightColorScheme(
    primary = Color(0xFF8230CE),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF1DAFF),
    onPrimaryContainer = Color(0xFF2B0052),
    inversePrimary = Color(0xFFDEB7FF),
    secondary = Color(0xFF665A6F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEDDDF6),
    onSecondaryContainer = Color(0xFF21182A),
    tertiary = Color(0xFF805258),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9DE),
    onTertiaryContainer = Color(0xFF321016),
    error = Color(0xFFBA1B1B),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD4),
    onErrorContainer = Color(0xFF410001),
    background = Color(0xFFFCFCFC),
    onBackground = Color(0xFF1D1B1E),
    surface = Color(0xFFFCFCFC),
    onSurface = Color(0xFF1D1B1E),
    surfaceVariant = Color(0xFFE9DFEB),
    onSurfaceVariant = Color(0xFF4A454D),
    inverseSurface = Color(0xFF322F33),
    inverseOnSurface = Color(0xFFF6EFF4),
    outline = Color(0xFF7C757F),
)

val DarkColorScheme = darkColorScheme(
    primary = Color(0xFFDEB7FF),
    onPrimary = Color(0xFF480082),
    primaryContainer = Color(0xFF6800B4),
    onPrimaryContainer = Color(0xFFF1DAFF),
    inversePrimary = Color(0xFF8230CE),
    secondary = Color(0xFFD0C1D9),
    onSecondary = Color(0xFF362C3F),
    secondaryContainer = Color(0xFF4D4356),
    onSecondaryContainer = Color(0xFFEDDDF6),
    tertiary = Color(0xFFF3B7BE),
    onTertiary = Color(0xFF4B252B),
    tertiaryContainer = Color(0xFF653A40),
    onTertiaryContainer = Color(0xFFFFD9DE),
    error = Color(0xFFFFB4A9),
    onError = Color(0xFF680003),
    errorContainer = Color(0xFF930006),
    onErrorContainer = Color(0xFFFFDAD4),
    background = Color(0xFF1D1B1E),
    onBackground = Color(0xFFE7E1E5),
    surface = Color(0xFF1D1B1E),
    onSurface = Color(0xFFE7E1E5),
    surfaceVariant = Color(0xFF4A454D),
    onSurfaceVariant = Color(0xFFCCC4CE),
    inverseSurface = Color(0xFFE7E1E5),
    inverseOnSurface = Color(0xFF1D1B1E),
    outline = Color(0xFF968E99),
)